### ISSUE TITLE
Logica de partida

### ISSUE THREAD

**Issue by Juanguppy** [UNIZAR-30226-2024-02/Front-end-web#38]

**Comment by 737275** [comment]
Un par de problemas que he detectado en las pruebas:
1) Ha desaparecido el número de tropas por colocar en la fase de colocación.
2) A veces las skins tienen el enlace roto cuando se inicia una partida, en el navegador Edge.

**Comment by 737275** [comment]
Lleva terminada ya un tiempecico.
