### ISSUE TITLE
Implementar perfil de usuario

### ISSUE THREAD

**Issue by Juanguppy** [UNIZAR-30226-2024-02/Front-end-web#39]
- La pantalla que estuvimos hablando con el avatar y las dos opciones (gestionar skins + historico) con botones o incluso totalmente integradas en el propio perfil

**Comment by 737275** [comment]
Podría tener sentido unificar la pantalla de perfil completamente con la de skins, histórico y amigos (únicamente en la aplicación web) a modo de dashboard. Se podría implementar un pequeño resumen con un botón hacia las pantallas con las listas completas o directamente incluir las listas enteras con el paginado, aunque puede que se vea demasiado pequeño y la pantalla algo sobrecargada.

De momento he mantenido los botones, dejo el issue abierto. Si lo llegamos a ver necesario se puede implementar.

**Comment by 737275** [comment]
Lo he hablado con @Juanguppy y había entendido mal el issue, lo cierro dado que lo pedido está implementado.

**Comment by 737275** [comment]
Arreglados los problemas de estilos.
