### ISSUE TITLE
botones volver

### ISSUE THREAD

**Issue by carloschu117** [UNIZAR-30226-2024-02/Front-end-web#41]

**Comment by 737275** [comment]
En la página de skins, el botón de volver estaba implementado de esta manera (que me fallaba):

<button onclick="window.location.href='/perfil'">Atrás</button>

Lo he cambiado a la implementación en las demás pantallas:

<button class="button" routerLink="/perfil">Atrás</button>

Atención a que todos los botones, incluso los viejos, funcionen.
