### ISSUE TITLE
Reintentar

### ISSUE THREAD

**Issue by Juanguppy** [UNIZAR-30226-2024-02/Front-end-web#55]
- Cada llamada al back end que falle, hacer lo siguiente: 
- Llamar a obtenerPartida para obtener el estado real 
- Esperar X segundos , y si esta ha fallado, esperar X+d segundos
- Si esta vuelve a fallar, X+2d segundos
- Y así hasta un número N de intentos. Si tras estos no se consigue, mostrar error de FATAL ERROR SERVER CAÍDO y tirar al usuario de la partida o algo así 
- Sería un while o algo así

**Comment by Juanguppy** [comment]
va relacionado con lo de #42 por eso te lo asocio @815770 es fácil de hacer y de paso te sirve para entender más lo que hemos implementado de la partida en web y así entiendes más nuestro código que creo que es algo bueno
si te va mal lo hago yo o @737275

**Comment by Juanguppy** [comment]
va relacionado con lo de #42 por eso te lo asocio @815770 es fácil de hacer y de paso te sirve para entender más lo que hemos implementado de la partida en web y así entiendes más nuestro código que creo que es algo bueno
si te va mal lo hago yo o @737275

**Comment by 815770** [comment]
Cuando acabe lo de la lógica me pondré con esto

**Comment by Juanguppy** [comment]
@815770 lo has hecho o has decidido que no lo vamos a implementar?

**Comment by 815770** [comment]
La he cerrado por error
